# Metadata
sonar.projectKey=scanoss-demo-repo
sonar.projectName=Demo Repo - Full DNA Audit
sonar.projectVersion=1.0

# Paths
sonar.sources=src, vendor, legacy
sonar.exclusions=testenv/**, **/*.json

# Lenguages
sonar.language=c,cpp,py

# SCANOSS Intergation

sonar.externalIssuesReportPaths=scanoss_sonar_report.json

sonar.sourceEncoding=UTF-8
